name: Run Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        env:
          UV_HTTP_TIMEOUT: 300
        run: uv pip install -e ".[test]"
      - name: Run tests
        run: uv run pytest